export const RECEIPT_BRANDING = {
  name: 'PharmaCare Pharmacy',
  address: 'Shop 12, City Medical Plaza · Lahore',
  phone: 'Tel: +92 300 5550199',
  footerThanks: 'Thank you for your visit — stay well.',
  footerPolicy: 'Returns accepted within 7 days with original packaging & receipt.',
  footerSystem: 'Generated by PharmaOS POS',
} as const;
